### ISSUE TITLE
Not compatible with ReWorked version

### ISSUE THREAD

**Issue by ArchiDreamZ** [Jedibrine/attackindicators#1]
Can start the game, but crashes when entering the save file

Here are the details：
[crash-2024-01-24_20.13.11-client.txt](https://github.com/Jedibrine/attackindicators/files/14038054/crash-2024-01-24_20.13.11-client.txt)

[latest.log](https://github.com/Jedibrine/attackindicators/files/14038058/latest.log)

[fml-client-3.log](https://github.com/Jedibrine/attackindicators/files/14038062/fml-client-3.log)

**Comment by Jedibrine** [comment]
For now I am not sure if I can make it compatible with Reworked, so closing this. Make sure to use LOTR Improvements instead of the stand-alone attack indicators
